name: 'Generate SBOM'
description: 'Generate SBOM from an oci images'
inputs:
  images:
    description: "Full image paths to generate SBOMs for."
    required: true
  format:
    description: "SBOM format (json, text, cyclonedx, cyclonedx-json, spdx, spdx-json, table)"
    required: true
    default: "json"
  sign:
    description: "Sign SBOM with cosign"
    required: false
    default: 'false'
  attest:
    description: "Attest the images with the generated SBOMs"
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Setup Syft
      id: setup
      uses: anchore/sbom-action/download-syft@3626d7d7b13e87ee6c6f9ded3940dea05a3967bc

    - name: Generate SBOM
      run: echo "${{ inputs.images }}" | grep -v "^$" | while read -r a; do syft $a -o ${{ inputs.format }} | jq --compact-output > $a; done
      shell: sh

    - name: Sign SBOM
      if: ${{ inputs.sign == 'true' }}
      run: echo "${{ inputs.images }}" | grep -v "^$" | while read -r a; do cosign sign-blob --output-signature $a.sig $a; done
      shell: sh
      env:
        COSIGN_EXPERIMENTAL: "1"

    - name: Attest images with SBOM
      if: ${{ inputs.attest == 'true' }}
      run: echo "${{ inputs.images }}" | grep -v "^$" | while read -r a; do cosign attest -f --type spdx --predicate $a $a; done
      shell: sh
      env:
        COSIGN_EXPERIMENTAL: "1"
