name: 'Generate SLSA Provenance'
description: 'Generate SLSA Provenance from artifacts'
inputs:
  action-sha:
    description: "SHA of this action used (needed for extra material)."
    required: true
  images:
    description: "Full image paths to generate provenances for."
    required: true
  artifact-path:
    description: "Path of artifacts"
    required: true
  output:
    description: "Output file"
    required: true
    default: "provenance.json"
  sign:
    description: "Sign provenance with cosign"
    required: false
    default: 'false'
  attest:
    description: "Attest the image with the generated provenance"
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Create additional material
      shell: bash
      run: |
        echo "[{\"uri\": \"git+https://github.com/ckotzbauer/actions-toolkit\",\"digest\": {\"sha1\": \"${{ inputs.action-sha }}\"}}]" > material.json

    - name: Generate provenance
      uses: philips-labs/slsa-provenance-action@33ba3da2213c83ce02df0f2f6ba925ec79037f9d
      with:
        artifact_path: ${{ inputs.artifact-path }}
        output_path: ${{ inputs.output }}
        extra_materials: |
          material.json

    - name: Sign Provenance
      if: ${{ inputs.sign == 'true' }}
      run: cosign sign-blob --oidc-issuer=https://token.actions.githubusercontent.com --output-signature ${{ inputs.output }}.sig ${{ inputs.output }}
      shell: sh
      env:
        COSIGN_EXPERIMENTAL: "1"

    - name: Attest images with Provenance
      if: ${{ inputs.attest == 'true' }}
      run: echo "${{ inputs.images }}" | grep -v "^$" | while read -r a; do cosign attest --oidc-issuer=https://token.actions.githubusercontent.com -f --predicate ${{ inputs.output }} $a; done
      shell: sh
      env:
        COSIGN_EXPERIMENTAL: "1"
