name: 'Push release'
description: 'Push changes and create GitHub Release'
inputs:
  github-token:
    description: "GitHub Token used to authenticate against a repository for Git context"
    default: ${{ github.token }}
    required: false
  version:
    description: "Release version."
    required: true
  branch:
    description: "Git branch."
    default: main
    required: false
  pat:
    description: "PAT with repo-access"
    required: true
  files:
    description: "Files to upload for the release"
    required: false
runs:
  using: "composite"
  steps:
    - name: Commit files
      shell: sh
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "chore: release ${{ inputs.version }}" -a

    - name: Push changes
      uses: ad-m/github-push-action@8407731efefc0d8f72af254c74276b7a90be36e1
      with:
        github_token: ${{ inputs.pat }}
        branch: ${{ inputs.branch }}

    - name: Create release
      uses: softprops/action-gh-release@8a65c813553f4d05769635eb1b70180d25b9b61b
      with:
        name: ${{ inputs.version }}
        tag_name: ${{ inputs.version }}
        body_path: commits.md
        files: ${{ inputs.files }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
