name: 'Docker image creation'
description: 'Build, push and sign docker images'
inputs:
  github-token:
    description: "GitHub Token used to authenticate against a repository for Git context"
    default: ${{ github.token }}
    required: true
  # docker params from docker/build-push-action
  push:
    description: "Push is a shorthand for --output=type=registry"
    required: false
    default: 'false'
  platforms:
    description: "List of target platforms for build"
    required: false
  context:
    description: "Build's context is the set of files located in the specified PATH or URL"
    required: false
  file:
    description: "Path to the Dockerfile"
    required: false
  labels:
    description: "List of metadata for an image"
    required: false
  load:
    description: "Load is a shorthand for --output=type=docker"
    required: false
    default: 'false'
  build-args:
    description: "List of build-time variables"
    required: false
  tags:
    description: "List of tags"
    required: true
  registry-password:
    description: "Password of the container registry."
    required: true
  # signing parameters
  sign:
    description: "Sign image with cosign"
    required: false
    default: 'false'
  cosign-password:
    description: "Cosign password"
    required: false
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@10348241d3ea2d30357b172897afc31824ea2e2e

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25

    - name: GHCR Login
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.registry-password }}

    - name: Build image
      uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229
      with:
        github-token: ${{ inputs.github-token }}
        push: ${{ inputs.push }}
        platforms: ${{ inputs.platforms }}
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        labels: ${{ inputs.labels }}
        load: ${{ inputs.load }}
        build-args: ${{ inputs.build-args }}
        tags: ${{ inputs.tags }}

    - name: Sign image
      if: ${{ inputs.sign == 'true' }}
      run: echo "${{ inputs.tags }}" | while read -r a; do echo cosign sign --key cosign.key -f -r $a; done
      shell: sh
      env:
        COSIGN_PASSWORD: ${{ inputs.cosign-password }}
        COSIGN_EXPERIMENTAL: "1"
