
name: Test

on:
  push:

jobs:
  slsa-provenance:
    runs-on: ubuntu-latest
    steps:
      - name: Setup cosign
        uses: sigstore/cosign-installer@v1.4.1

      - name: Prepare action
        shell: bash
        run: |
          mkdir -p dist/
          echo "Test asset 1" > dist/asset1.txt
          echo "Test asset 2" > dist/asset2.txt
          cosign generate-key-pair
        env:
          COSIGN_PASSWORD: 123$

      - name: GHCR Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ckotzbauer
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Run action
        uses: ./slsa-provenance
        with:
          action-sha: "aaaaabbbbbccccc"
          image: ghcr.io/ckotzbauer/actions-toolkit/test-image:1.0.0
          artifact-path: dist/
          sign: true
          attest: true
          cosign-password: 123$

      - name: Verify action
        shell: bash
        run: |
          cat provenance.json | jq -r '.predicate.materials[] | select(.digest.sha1=="aaaaabbbbbccccc") | .digest.sha1' | grep aaaaabbbbbccccc
          cosign verify-blob --key cosign.pub --signature provenance.json.sig provenance.json
          cosign verify-attestation --key cosign.pub ghcr.io/ckotzbauer/actions-toolkit/test-image:1.0.0
