name: Create default labels
on:
  push:
    branches:
      - "main"
    paths:
      - ".github/labels.yml"
jobs:
  labels:
    name: DefaultLabelsActions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          manifest: .github/labels.yml
