name: Create default labels
on:
  push:
    branches:
      - "main"
    paths:
      - ".github/labels.yml"
jobs:
  labels:
    name: DefaultLabelsActions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3ba5ee6fac7e0e30e2ea884e236f282d3a775891
      - uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          manifest: .github/labels.yml
