name: Release Toolkit

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@230611dbd0eb52da1e1f4f7bc8bb0c3a339fc8b7
        with:
          fetch-depth: 0
          token: ${{ secrets.REPO_ACCESS }}

      - name: Update versions
        shell: bash
        run: |
          LAST_TAG=$(git describe --abbrev=0 --tags)
          find .github/workflows/toolkit-*.yml | while read -r a; do
              sed -i "s#@${LAST_TAG}#@${{ github.event.inputs.version }}#g" $a;
              sed -i "s#action-sha: \"${LAST_TAG}\"#action-sha: \"${{ github.event.inputs.version }}\"#g" $a;
          done

      - name: Generate Changelog
        uses: ckotzbauer/changelog-generator@f9174538ca28860c604fd00c68523a7bf6b8b27e
        with:
          release-version: ${{ github.event.inputs.version }}
          github-handle: ${{ github.repository }}
          commit-output: commits.md

      - name: Push release
        uses: ckotzbauer/actions-toolkit/push-release@0.2.0
        with:
          version: ${{ github.event.inputs.version }}
          pat: ${{ secrets.REPO_ACCESS }}
