name: test-action

on:
  push:

jobs:
  test-action:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - slsa-provenance
    steps:
    - uses: actions/checkout@v2

    - uses: dorny/paths-filter@v2.10.2
      id: changes
      with:
        filters: |
          src:
            - "${{ matrix.module }}/**"

    - name: Run test
      if: steps.changes.outputs.src == 'true'
      shell: bash
      run: |
        act -W __tests__ -j ${{ matrix.module }} --bind -s GITHUB_TOKEN=${{ secrets.REPO_ACCESS }} -s GHCR_PASSWORD=${{ secrets.GHCR_PASSWORD }}
