name: test-action

on:
  push:

jobs:
  test-action:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - slsa-provenance
    steps:
    - uses: actions/checkout@v2

    - uses: dorny/paths-filter@v2.10.2
      id: changes
      with:
        filters: |
          src:
            - "${{ matrix.module }}/**"
            - ".github/workflows/test-action.yml"

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Setup act
      run: go install github.com/nektos/act@master
      shell: bash

    - name: Run test
      if: steps.changes.outputs.src == 'true'
      shell: bash
      run: |
        act \
          -W __tests__ \
          -j ${{ matrix.module }} \
          --bind \
          -s GITHUB_TOKEN=${{ secrets.REPO_ACCESS }} \
          -s GHCR_PASSWORD=${{ secrets.GHCR_PASSWORD }} \
          -P ubuntu-latest=ghcr.io/catthehacker/ubuntu:act-latest
