name: Create default labels

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  create-default-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lannonbr/issue-label-manager-action@3.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          delete: true
