name: Create default labels

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  create-default-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          manifest: .github/labels.yml
